### ISSUE TITLE
Provide an easy way to migrate everything in kubeconfig into the password manager

### ISSUE THREAD

**Issue by utkuozdemir** [chrisns/kubectl-passman#200]
I have many contexts in my kubeconfig file with many credentials.
I also have additional kubeconfig files in various locations which I sometimes switch to by doing `export KUBECONFIG=<path>`

It would be great if there was a simple way to migrate all these kubeconfigs to get their credentials from the password manager using a single or a few commands.

**Comment by chrisns** [comment]
Hi,
That's a great idea, I'd be personally nervous about migrating quite so broadly, a shell script might be a reasonable approach for your use case.
Happy to revisit this if there's wider demand.
Thanks
